# Generated by Django 4.1.3 on 2022-11-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
    ]
